HW4/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index', as: :home

  get 'users/:id/posts' => 'users#user_show_posts'

  get '/posts' => 'posts#index', as: :posts

  resources :users do
    resources :posts
  end

end

HW4/app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user

end

HW4/app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts

end

HW4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

HW4/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

HW4/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@post = Post.all
	end

end

HW4/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		id = params[:id]
		@user = User.find(id)
	end

	def user_show_posts
		id = params[:id]
		@user = User.find(id)
	end

	def destroy
		u = User.find(params[:id])
		if u.delete
			flash[:notice] = "User has been deleted."
			redirect_to home_path
		else
			flash[:notice] = "Something went wrong."
		end
	end

end

HW4/app/helpers/application_helper.rb
module ApplicationHelper
end

HW4/app/helpers/home_helper.rb
module HomeHelper
end

HW4/app/helpers/posts_helper.rb
module PostsHelper
end

HW4/app/helpers/user_helper.rb
module UserHelper
end

HW4/app/views/home/index.html.erb
<!DOCTYPE html>

<%= flash[:notice] if flash[:notice] %>

<h3>Home Page</h3>

HW4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HW4 - Understand RESTful Routing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<ul>
		<li>
			<%= link_to 'Home Page', home_path %>
		</li>
		<li>
			<%= link_to 'Users Portal', users_path %>
		</li>
		<li>
			<%= link_to 'Posts Page', posts_path %>
		</li>
	</ul>



<%= yield %>

	<ol>
		<li>
			<del>
				Understand RESTful routing and how to create the routing necessary for an arbitrary resource in Rails Assignment
			</del>
		</li>
		<li>
			<del>
				Make a new Rails app from the ground up. Create a User model and a Post model.  Associate the models so that one User can have many Posts.
			</del>
		</li>
		<li>
			<del> 
				Create a RESTful routing scheme that allows the display of a user at /users/:id, a list of all the users at /users, and the ability to delete a user by sending a DELETE request to / users/:id. 
			</del>
		</li>
		<li>
			<del>
				Create a nested resource for posts (see <a target="_blank" href="http://guides.rubyonrails.org/routing.html#nested-resources">the documentation</a>) that allows you to see all of a user’s posts at /users/:id/posts
			</del>
		</li>	
	</ol>

</body>
</html>

HW4/app/views/posts/index.html.erb
<!DOCTYPE html>


<h3>Posts Page</h3>

<ul>
	<% @post.reverse.each do |p| %>
		<li>
			<%= p.title %><br>
			<%= p.body %><br>
			
		</li>
	<% end %>
</ul>

HW4/app/views/users/index.html.erb
<!DOCTYPE html>

<h3>Users Page</h3>

<ul>
	<% @users.all.each do |u| %>
		<li>
			<%= "#{u.fname} #{u.lname} - #{u.id}" %><br>
			<%= "#{u.posts.last.title}" %><br>
			<%= "#{u.posts.last.body}" %>
		</li>
	<% end %>
</ul>

HW4/app/views/users/show.html.erb
<!DOCTYPE html>

<h3><%= "#{@user.fname}'s Page" %></h3>

<h4>Posts:</h4>

<ul>
	<% @user.posts.all.each do |p| %>
	<li>
		<%= p.title %><br>
		<%= p.body %>
	</li>
	<% end %>
</ul>


<div>
<%= link_to "Delete User", user_path(@user), method: :delete %>
</div>

HW4/app/views/users/user_show_posts.html.erb
<!DOCTYPE html>

<ul>
	<% @user.posts.reverse.each do |p| %>
	<li>
		<%= p.title %><br>
		<%= p.body %>
	</li>
	<% end %>
</ul>